### ISSUE TITLE
Add Badge Number Display to Screen Corners

### ISSUE THREAD

**Issue by dogpixels** [eurofurence/reg-onsite-ui#16]
The badge number is currently displayed in a leftmost input field in the detailed attendee view, suffixed by its checksum letter, e.g. "42G".
This number is then given to the "runner", who typically stands behind the person at the computer, to go fetch the according badge. In many occasions, the runner would proactively look for the badge number to quicken the process a little further.

**Suggestion**: display the badge number (without the checksum letter, in that case only "42") in huge letters in the top left and top right corner of the screen. This would allows the runner to spot the number more easily and from afar, hopefully reducing the bustle of runners moving back and forth between counter and badge repository.

**Comment by RakanHowls** [comment]
Implemented in Version EF28-1.0
