### ISSUE TITLE
Prevent re-auto-selection after checkin

### ISSUE THREAD

**Issue by RakanHowls** [eurofurence/reg-onsite-ui#3]
If there are just two matching attendees and the first one is clicked and checked out, the auto-selection should not trigger again!

**Comment by dogpixels** [comment]
Ohhh that's what this was! I noticed a rare glitchy behavior but couldn't possibly describe under what circumstances it'd appear. Checked in poor Nerkitt by accident that way. x)

**Comment by RakanHowls** [comment]
@dogpixels Ahh - Yes! That's why I suggested to everyone at the regdesk to drop the "status" filter, since that "fixed" the issue in a way (the checked-in attendee didn't disappear from the search results...)

**Comment by RakanHowls** [comment]
Fixed in https://github.com/eurofurence/reg-onsite-ui/commit/c3a64a631e0658e530c0083bea5657c2db0ab601
